### ISSUE TITLE
yii 2.0 plugin for netbeans..

### ISSUE THREAD

**Issue by manuclues** [nbphpcouncil/nb-yii-plugin#57]
is there any way by which I can implement "Yii 2 basic" using the existing netbeans plugin? coz yii/framework/yiic.php doesn't exist in yii 2 basic and a yii project cnt be created!

**Comment by Mariotrol4** [comment]
entonces como puedo editar la platilla basica del yii2

**Comment by Mariotrol4** [comment]
como puedo editar la platilla basica del yii2  o sera posible utilizar cualquier  editor php
