### ISSUE TITLE
NetBeans 8.0.2: Configuration is not valid.

### ISSUE THREAD

**Issue by kizanlik** [nbphpcouncil/nb-yii-plugin#63]
Hi,

When I create a new PHP project in NetBeans 8.0.2, I receive "Configuration of Yii PHP Web Framework is not valid.

A screen shot is attached.

NetBeans PHP Yii Framework plug-in version is 0.8.1

![screen shot 2015-02-16 at 16 48 45](https://cloud.githubusercontent.com/assets/11030843/6213774/d3414162-b5fb-11e4-9821-1b2a5ed841db.png)
"

**Comment by junichi11** [comment]
Did you look README file? https://github.com/nbphpcouncil/nb-yii-plugin#new-yii-project-wizard
