### ISSUE TITLE
Variables not showing with findByPk

### ISSUE THREAD

**Issue by 3dgroup** [nbphpcouncil/nb-yii-plugin#65]
I have just upgraded from Netbeans 7 to 8 and now i am having issues with findByPk. For some reason no variables are showing on the autocomplete:

$model = CustomerStatement::model()->findByPk($id);
$model-> shows functions like addError but no vars
$model = new CustomerStatement();
$model-> shows everything correct

**Comment by junichi11** [comment]
It seems to work fine in my environment.

![nb-yii-plugin-issue65](https://cloud.githubusercontent.com/assets/738383/7729152/2bc5eab8-ff4e-11e4-87c1-33b26c346d0a.png)

Product Version: NetBeans IDE 8.0.2 (Build 201408251540)
Java: 1.7.0_80; Java HotSpot(TM) Client VM 24.80-b11
Runtime: Java(TM) SE Runtime Environment 1.7.0_80-b15
System: Linux version 3.2.0-83-generic-pae running on i386; UTF-8;

**Comment by 3dgroup** [comment]
AccountID doesn't show
![findallbypk](https://cloud.githubusercontent.com/assets/3091597/7744788/072382b0-ff9e-11e4-957c-0c5a17bf19d0.png)
AccountID does show:
![search](https://cloud.githubusercontent.com/assets/3091597/7744790/0b022fbc-ff9e-11e4-80bb-3ff59212794a.png)

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.7.0_21; Java HotSpot(TM) 64-Bit Server VM 23.21-b01
Runtime: Java(TM) SE Runtime Environment 1.7.0_21-b11
System: Windows 7 version 6.1 running on amd64; Cp1252; en_GB (nb)

**Comment by 3dgroup** [comment]
In this image I noticed I put findAllByPK, but its the same with findByPK aswell.

**Comment by rob006** [comment]
Which version of yii you imported in project Include Path?

**Comment by 3dgroup** [comment]
1.1.14

**Comment by rob006** [comment]
Try the latest version - it use `static` in phpdoc for these methods, so syntax suggestions should work fine.

**Comment by 3dgroup** [comment]
updating Yii worked

**Comment by junichi11** [comment]
@rob006 Thanks.

Generally, a code completion's problem is not this plugin's one because Method and variable completions are standard feature of NetBeans.
