### ISSUE TITLE
Incompatible NB 8.1

### ISSUE THREAD

**Issue by finzaiko** [nbphpcouncil/nb-yii-plugin#66]
I still using yii1, when I update netbean to the newest version 8.1 but can not generate new app and when I open the project can not right click to do something (close/properties)

Thanks in advance for fix this

**Comment by junichi11** [comment]
Thanks for reporting it. I'll fix it later.

**Comment by junichi11** [comment]
@finzaiko I've fixed it. Could you test it? https://github.com/nbphpcouncil/nb-yii-plugin/releases/tag/v0.9.0 

Thanks.

**Comment by finzaiko** [comment]
It fine when I create a new project.
Right click on opened project not work and got error notification : A java.lang.IndexOutOfBoundsExeption

**Comment by junichi11** [comment]
Oh... I'll look at it later. Please wait a while.

**Comment by junichi11** [comment]
@finzaiko Could you confirm whether PHP is active in Tools > Plugins? If it's not active, please change to active.

Thanks.

**Comment by finzaiko** [comment]
Oh sorry, you right because of that I'm not activate before, all work fine now.
Thanks alot for your help.
