### ISSUE TITLE
feature request : $form-> code completion

### ISSUE THREAD

**Issue by indrasaputrawardhana** [nbphpcouncil/nb-yii-plugin#69]
Hello developer,

I need this feature which is missing in your plugin, 
in view files , $form-> [ctrl space] , it would be alot easier to program if we dont have to take a look at Yii $form reference if it's accomodated, https://snag.gy/t1nVEd.jpg
Hope to hear from you 

regards

**Comment by Chris2011** [comment]
What was the reason to close it? Is it implemented?

**Comment by indrasaputrawardhana** [comment]
I found the solution here , http://stackoverflow.com/questions/24663687/yii-framework-in-netbeans-object-method-autocomplete-not-appearing and it works as expected, try to follow along the tutorial there  :)) 
and while you're programming yii2 it doesnt need any plugin what soever

**Comment by Chris2011** [comment]
Ok thx.
