### ISSUE TITLE
Cannot install plugin on Netbeans 12.4

### ISSUE THREAD

**Issue by wardjk** [nbphpcouncil/nb-yii-plugin#71]
README: "Install Plugin" says "Download a nbm file...". Where is the latest nbm file for nb-yii-plugin? 
It is no longer available from the previous source: http://plugins.netbeans.org.
The plugin is also not available from the new source: https://plugins.netbeans.apache.org
The most recent copy I have is from 2015 named org-nbphpcouncil-modules-php-yii-0.9.2.nbm
I tried to install it and received the message:
_Some plugins require plugin PHP Editor to be installed.
The plugin PHP Editor is requested in implementation version 2.
The following plugin is affected:
PHP Yii Framework (NetBeans.PHPCC)_

**Comment by junichi11** [comment]
Fixed. Please give it a try (0.10.0): https://github.com/nbphpcouncil/nb-yii-plugin/releases/tag/v0.10.0
